/**
 * ID Card Template Definitions
 * 20+ pre-designed professional templates
 */

export interface CardElement {
  id: string
  type: 'rectangle' | 'circle' | 'text' | 'image' | 'qrcode' | 'line'
  x: number
  y: number
  width?: number
  height?: number
  radius?: number
  text?: string
  fontSize?: number
  fontWeight?: 'normal' | 'bold' | 'semibold'
  color?: string
  backgroundColor?: string
  borderColor?: string
  borderWidth?: number
  source?: string // for images and QR codes
  align?: 'left' | 'center' | 'right'
  opacity?: number
}

export interface CardTemplate {
  id: string
  name: string
  category: string
  description: string
  width: number // in inches
  height: number // in inches
  backgroundColor: string
  elements: CardElement[]
  thumbnail?: string
  isActive: boolean
  isDefault: boolean
}

export const CARD_TEMPLATES: CardTemplate[] = [
  // 1. Modern Blue Professional
  {
    id: 'template-modern-blue',
    name: 'Modern Blue',
    category: 'Professional',
    description: 'Clean blue design with modern typography',
    width: 3.375,
    height: 2.125,
    backgroundColor: '#ffffff',
    isActive: true,
    isDefault: true,
    elements: [
      {
        id: 'header-bg',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 3.375,
        height: 0.6,
        backgroundColor: '#003d99',
      },
      {
        id: 'logo',
        type: 'image',
        x: 0.15,
        y: 0.1,
        width: 0.4,
        height: 0.4,
        source: '{{logo_url}}',
      },
      {
        id: 'company-name',
        type: 'text',
        x: 0.65,
        y: 0.15,
        width: 2.6,
        height: 0.3,
        text: '{{company_name}}',
        fontSize: 16,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'left',
      },
      {
        id: 'employee-photo',
        type: 'image',
        x: 0.2,
        y: 0.8,
        width: 0.9,
        height: 1.15,
        source: '{{employee_photo}}',
        borderColor: '#003d99',
        borderWidth: 2,
      },
      {
        id: 'employee-name',
        type: 'text',
        x: 1.2,
        y: 0.8,
        width: 1.95,
        height: 0.25,
        text: '{{employee_name}}',
        fontSize: 13,
        fontWeight: 'bold',
        color: '#003d99',
        align: 'left',
      },
      {
        id: 'employee-id',
        type: 'text',
        x: 1.2,
        y: 1.1,
        width: 1.95,
        height: 0.15,
        text: 'ID: {{employee_id}}',
        fontSize: 10,
        fontWeight: 'bold',
        color: '#666666',
        align: 'left',
      },
      {
        id: 'designation',
        type: 'text',
        x: 1.2,
        y: 1.3,
        width: 1.95,
        height: 0.2,
        text: '{{designation_name}}',
        fontSize: 10,
        color: '#666666',
        align: 'left',
      },
      {
        id: 'location',
        type: 'text',
        x: 1.2,
        y: 1.55,
        width: 1.95,
        height: 0.15,
        text: '{{location_name}}',
        fontSize: 9,
        color: '#888888',
        align: 'left',
      },
      {
        id: 'qr-code',
        type: 'qrcode',
        x: 2.85,
        y: 0.8,
        width: 0.45,
        height: 0.45,
        source: '{{verification_url}}',
      },
      {
        id: 'valid-from',
        type: 'text',
        x: 2.85,
        y: 1.35,
        width: 0.45,
        height: 0.1,
        text: 'From: {{id_valid_from_short}}',
        fontSize: 7,
        color: '#999999',
        align: 'left',
      },
      {
        id: 'valid-until',
        type: 'text',
        x: 2.85,
        y: 1.5,
        width: 0.45,
        height: 0.1,
        text: 'Until: {{id_valid_until_short}}',
        fontSize: 7,
        color: '#999999',
        align: 'left',
      },
    ],
  },

  // 2. Corporate Red
  {
    id: 'template-corporate-red',
    name: 'Corporate Red',
    category: 'Professional',
    description: 'Bold red accent design for executive roles',
    width: 3.375,
    height: 2.125,
    backgroundColor: '#ffffff',
    isActive: true,
    isDefault: false,
    elements: [
      {
        id: 'left-accent',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 0.1,
        height: 2.125,
        backgroundColor: '#cc0000',
      },
      {
        id: 'header-line',
        type: 'line',
        x: 0.1,
        y: 0.5,
        width: 3.275,
        height: 0,
        borderColor: '#cc0000',
        borderWidth: 2,
      },
      {
        id: 'logo',
        type: 'image',
        x: 0.2,
        y: 0.08,
        width: 0.35,
        height: 0.35,
        source: '{{logo_url}}',
      },
      {
        id: 'company-name',
        type: 'text',
        x: 0.65,
        y: 0.12,
        width: 2.6,
        height: 0.25,
        text: '{{company_name}}',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#cc0000',
        align: 'left',
      },
      {
        id: 'employee-photo',
        type: 'image',
        x: 0.2,
        y: 0.7,
        width: 0.85,
        height: 1.25,
        source: '{{employee_photo}}',
        borderColor: '#cc0000',
        borderWidth: 3,
      },
      {
        id: 'info-bg',
        type: 'rectangle',
        x: 1.1,
        y: 0.7,
        width: 2.175,
        height: 1.25,
        backgroundColor: '#f5f5f5',
      },
      {
        id: 'employee-name',
        type: 'text',
        x: 1.25,
        y: 0.8,
        width: 1.95,
        height: 0.25,
        text: '{{employee_name}}',
        fontSize: 13,
        fontWeight: 'bold',
        color: '#000000',
        align: 'left',
      },
      {
        id: 'employee-id',
        type: 'text',
        x: 1.25,
        y: 1.1,
        width: 1.95,
        height: 0.15,
        text: 'ID: {{employee_id}}',
        fontSize: 10,
        fontWeight: 'bold',
        color: '#cc0000',
        align: 'left',
      },
      {
        id: 'designation',
        type: 'text',
        x: 1.25,
        y: 1.3,
        width: 1.95,
        height: 0.18,
        text: '{{designation_name}}',
        fontSize: 10,
        color: '#333333',
        align: 'left',
      },
      {
        id: 'qr-code',
        type: 'qrcode',
        x: 1.1,
        y: 1.5,
        width: 0.4,
        height: 0.4,
        source: '{{verification_url}}',
      },
    ],
  },

  // 3. Minimal Clean
  {
    id: 'template-minimal-clean',
    name: 'Minimal Clean',
    category: 'Modern',
    description: 'Minimalist design with focus on readability',
    width: 3.375,
    height: 2.125,
    backgroundColor: '#ffffff',
    isActive: true,
    isDefault: false,
    elements: [
      {
        id: 'company-name',
        type: 'text',
        x: 0.15,
        y: 0.1,
        width: 3.075,
        height: 0.25,
        text: '{{company_name}}',
        fontSize: 16,
        fontWeight: 'bold',
        color: '#000000',
        align: 'left',
      },
      {
        id: 'divider',
        type: 'line',
        x: 0.15,
        y: 0.4,
        width: 3.075,
        height: 0,
        borderColor: '#e0e0e0',
        borderWidth: 1,
      },
      {
        id: 'employee-photo',
        type: 'image',
        x: 0.15,
        y: 0.5,
        width: 0.95,
        height: 1.5,
        source: '{{employee_photo}}',
      },
      {
        id: 'employee-name',
        type: 'text',
        x: 1.2,
        y: 0.5,
        width: 2.025,
        height: 0.3,
        text: '{{employee_name}}',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#000000',
        align: 'left',
      },
      {
        id: 'employee-id-label',
        type: 'text',
        x: 1.2,
        y: 0.85,
        width: 0.5,
        height: 0.18,
        text: 'ID:',
        fontSize: 9,
        color: '#888888',
        align: 'left',
      },
      {
        id: 'employee-id',
        type: 'text',
        x: 1.75,
        y: 0.85,
        width: 1.45,
        height: 0.18,
        text: '{{employee_id}}',
        fontSize: 10,
        fontWeight: 'bold',
        color: '#000000',
        align: 'left',
      },
      {
        id: 'designation-label',
        type: 'text',
        x: 1.2,
        y: 1.08,
        width: 0.5,
        height: 0.16,
        text: 'Position:',
        fontSize: 9,
        color: '#888888',
        align: 'left',
      },
      {
        id: 'designation',
        type: 'text',
        x: 1.75,
        y: 1.08,
        width: 1.45,
        height: 0.16,
        text: '{{designation_name}}',
        fontSize: 9,
        color: '#000000',
        align: 'left',
      },
      {
        id: 'location-label',
        type: 'text',
        x: 1.2,
        y: 1.28,
        width: 0.5,
        height: 0.16,
        text: 'Location:',
        fontSize: 9,
        color: '#888888',
        align: 'left',
      },
      {
        id: 'location',
        type: 'text',
        x: 1.75,
        y: 1.28,
        width: 1.45,
        height: 0.16,
        text: '{{location_name}}',
        fontSize: 9,
        color: '#000000',
        align: 'left',
      },
      {
        id: 'phone-label',
        type: 'text',
        x: 1.2,
        y: 1.48,
        width: 0.5,
        height: 0.15,
        text: 'Phone:',
        fontSize: 8,
        color: '#888888',
        align: 'left',
      },
      {
        id: 'phone',
        type: 'text',
        x: 1.75,
        y: 1.48,
        width: 1.45,
        height: 0.15,
        text: '{{employee_phone}}',
        fontSize: 8,
        color: '#000000',
        align: 'left',
      },
      {
        id: 'qr-code',
        type: 'qrcode',
        x: 2.8,
        y: 1.5,
        width: 0.45,
        height: 0.45,
        source: '{{verification_url}}',
      },
    ],
  },

  // 4. Dark Theme
  {
    id: 'template-dark-theme',
    name: 'Dark Theme',
    category: 'Modern',
    description: 'Dark background with high contrast text',
    width: 3.375,
    height: 2.125,
    backgroundColor: '#1a1a1a',
    isActive: true,
    isDefault: false,
    elements: [
      {
        id: 'header-bg',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 3.375,
        height: 0.45,
        backgroundColor: '#2d2d2d',
      },
      {
        id: 'company-name',
        type: 'text',
        x: 0.15,
        y: 0.08,
        width: 3.075,
        height: 0.3,
        text: '{{company_name}}',
        fontSize: 15,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'left',
      },
      {
        id: 'employee-photo',
        type: 'image',
        x: 0.15,
        y: 0.6,
        width: 0.95,
        height: 1.4,
        source: '{{employee_photo}}',
        borderColor: '#ffcc00',
        borderWidth: 2,
      },
      {
        id: 'employee-name',
        type: 'text',
        x: 1.2,
        y: 0.6,
        width: 2.025,
        height: 0.28,
        text: '{{employee_name}}',
        fontSize: 13,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'left',
      },
      {
        id: 'employee-id',
        type: 'text',
        x: 1.2,
        y: 0.92,
        width: 2.025,
        height: 0.2,
        text: 'ID: {{employee_id}}',
        fontSize: 10,
        fontWeight: 'bold',
        color: '#ffcc00',
        align: 'left',
      },
      {
        id: 'designation',
        type: 'text',
        x: 1.2,
        y: 1.15,
        width: 2.025,
        height: 0.18,
        text: '{{designation_name}}',
        fontSize: 9,
        color: '#cccccc',
        align: 'left',
      },
      {
        id: 'location',
        type: 'text',
        x: 1.2,
        y: 1.35,
        width: 2.025,
        height: 0.18,
        text: '{{location_name}}',
        fontSize: 9,
        color: '#cccccc',
        align: 'left',
      },
      {
        id: 'qr-code',
        type: 'qrcode',
        x: 1.2,
        y: 1.68,
        width: 0.4,
        height: 0.4,
        source: '{{verification_url}}',
      },
    ],
  },

  // 5. Gradient Premium
  {
    id: 'template-gradient-premium',
    name: 'Gradient Premium',
    category: 'Premium',
    description: 'Elegant gradient background with premium styling',
    width: 3.375,
    height: 2.125,
    backgroundColor: '#f0f0f0',
    isActive: true,
    isDefault: false,
    elements: [
      {
        id: 'gradient-bg',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 3.375,
        height: 0.7,
        backgroundColor: '#003d99',
      },
      {
        id: 'accent-bar',
        type: 'rectangle',
        x: 0,
        y: 0.68,
        width: 3.375,
        height: 0.05,
        backgroundColor: '#ffb800',
      },
      {
        id: 'company-text',
        type: 'text',
        x: 0.15,
        y: 0.15,
        width: 3.075,
        height: 0.4,
        text: '{{company_name}}',
        fontSize: 18,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'left',
      },
      {
        id: 'employee-photo',
        type: 'image',
        x: 0.15,
        y: 0.85,
        width: 0.95,
        height: 1.25,
        source: '{{employee_photo}}',
        borderColor: '#003d99',
        borderWidth: 2,
      },
      {
        id: 'info-container',
        type: 'rectangle',
        x: 1.15,
        y: 0.85,
        width: 2.1,
        height: 1.25,
        backgroundColor: '#ffffff',
        borderColor: '#e0e0e0',
        borderWidth: 1,
      },
      {
        id: 'employee-name',
        type: 'text',
        x: 1.3,
        y: 0.95,
        width: 1.8,
        height: 0.25,
        text: '{{employee_name}}',
        fontSize: 13,
        fontWeight: 'bold',
        color: '#003d99',
        align: 'left',
      },
      {
        id: 'employee-id',
        type: 'text',
        x: 1.3,
        y: 1.23,
        width: 1.8,
        height: 0.15,
        text: 'ID: {{employee_id}}',
        fontSize: 9,
        fontWeight: 'bold',
        color: '#ffb800',
        align: 'left',
      },
      {
        id: 'designation',
        type: 'text',
        x: 1.3,
        y: 1.41,
        width: 1.8,
        height: 0.15,
        text: '{{designation_name}}',
        fontSize: 9,
        color: '#666666',
        align: 'left',
      },
      {
        id: 'location',
        type: 'text',
        x: 1.3,
        y: 1.58,
        width: 1.8,
        height: 0.15,
        text: '{{location_name}}',
        fontSize: 9,
        color: '#666666',
        align: 'left',
      },
      {
        id: 'qr-code',
        type: 'qrcode',
        x: 2.85,
        y: 1.68,
        width: 0.35,
        height: 0.35,
        source: '{{verification_url}}',
      },
    ],
  },

  // 6. Security Guard Theme
  {
    id: 'template-security-guard',
    name: 'Security Guard',
    category: 'Security',
    description: 'Bold design for security personnel',
    width: 3.375,
    height: 2.125,
    backgroundColor: '#ffffff',
    isActive: true,
    isDefault: false,
    elements: [
      {
        id: 'security-stripe-1',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 3.375,
        height: 0.08,
        backgroundColor: '#cc0000',
      },
      {
        id: 'security-stripe-2',
        type: 'rectangle',
        x: 0,
        y: 0.12,
        width: 3.375,
        height: 0.08,
        backgroundColor: '#003d99',
      },
      {
        id: 'company-name',
        type: 'text',
        x: 0.15,
        y: 0.25,
        width: 3.075,
        height: 0.2,
        text: '{{company_name}}',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#003d99',
        align: 'center',
      },
      {
        id: 'badge-text',
        type: 'text',
        x: 0.15,
        y: 0.48,
        width: 3.075,
        height: 0.12,
        text: 'VERIFIED SECURITY PERSONNEL',
        fontSize: 8,
        fontWeight: 'bold',
        color: '#cc0000',
        align: 'center',
      },
      {
        id: 'employee-photo',
        type: 'image',
        x: 0.2,
        y: 0.7,
        width: 0.9,
        height: 1.3,
        source: '{{employee_photo}}',
        borderColor: '#cc0000',
        borderWidth: 3,
      },
      {
        id: 'employee-name',
        type: 'text',
        x: 1.2,
        y: 0.7,
        width: 1.95,
        height: 0.25,
        text: '{{employee_name}}',
        fontSize: 13,
        fontWeight: 'bold',
        color: '#000000',
        align: 'left',
      },
      {
        id: 'employee-id',
        type: 'text',
        x: 1.2,
        y: 1.0,
        width: 1.95,
        height: 0.2,
        text: '{{employee_id}}',
        fontSize: 11,
        fontWeight: 'bold',
        color: '#cc0000',
        align: 'left',
      },
      {
        id: 'designation',
        type: 'text',
        x: 1.2,
        y: 1.25,
        width: 1.95,
        height: 0.18,
        text: '{{designation_name}}',
        fontSize: 10,
        color: '#333333',
        align: 'left',
      },
      {
        id: 'qr-code',
        type: 'qrcode',
        x: 2.75,
        y: 1.6,
        width: 0.5,
        height: 0.5,
        source: '{{verification_url}}',
      },
    ],
  },

  // 7. Corporate Teal
  {
    id: 'template-corporate-teal',
    name: 'Corporate Teal',
    category: 'Professional',
    description: 'Professional teal accent design',
    width: 3.375,
    height: 2.125,
    backgroundColor: '#ffffff',
    isActive: true,
    isDefault: false,
    elements: [
      {
        id: 'header',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 3.375,
        height: 0.55,
        backgroundColor: '#008080',
      },
      {
        id: 'company-name',
        type: 'text',
        x: 0.15,
        y: 0.1,
        width: 3.075,
        height: 0.35,
        text: '{{company_name}}',
        fontSize: 16,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'left',
      },
      {
        id: 'employee-photo',
        type: 'image',
        x: 0.15,
        y: 0.7,
        width: 0.9,
        height: 1.35,
        source: '{{employee_photo}}',
      },
      {
        id: 'name-bg',
        type: 'rectangle',
        x: 1.15,
        y: 0.7,
        width: 2.1,
        height: 0.3,
        backgroundColor: '#008080',
      },
      {
        id: 'employee-name',
        type: 'text',
        x: 1.3,
        y: 0.78,
        width: 1.8,
        height: 0.2,
        text: '{{employee_name}}',
        fontSize: 13,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'left',
      },
      {
        id: 'employee-id',
        type: 'text',
        x: 1.3,
        y: 1.05,
        width: 1.8,
        height: 0.15,
        text: 'ID: {{employee_id}}',
        fontSize: 9,
        fontWeight: 'bold',
        color: '#008080',
        align: 'left',
      },
      {
        id: 'designation',
        type: 'text',
        x: 1.3,
        y: 1.23,
        width: 1.8,
        height: 0.15,
        text: '{{designation_name}}',
        fontSize: 9,
        color: '#333333',
        align: 'left',
      },
      {
        id: 'department',
        type: 'text',
        x: 1.3,
        y: 1.41,
        width: 1.8,
        height: 0.15,
        text: '{{department_name}}',
        fontSize: 9,
        color: '#666666',
        align: 'left',
      },
      {
        id: 'qr-code',
        type: 'qrcode',
        x: 1.15,
        y: 1.65,
        width: 0.4,
        height: 0.4,
        source: '{{verification_url}}',
      },
    ],
  },

  // 8. Gold Accent Luxury
  {
    id: 'template-gold-luxury',
    name: 'Gold Luxury',
    category: 'Premium',
    description: 'Luxury design with gold accents',
    width: 3.375,
    height: 2.125,
    backgroundColor: '#f9f7f3',
    isActive: true,
    isDefault: false,
    elements: [
      {
        id: 'top-accent',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 3.375,
        height: 0.15,
        backgroundColor: '#d4af37',
      },
      {
        id: 'company-name',
        type: 'text',
        x: 0.15,
        y: 0.25,
        width: 3.075,
        height: 0.2,
        text: '{{company_name}}',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#2c2c2c',
        align: 'center',
      },
      {
        id: 'divider',
        type: 'line',
        x: 0.3,
        y: 0.48,
        width: 2.775,
        height: 0,
        borderColor: '#d4af37',
        borderWidth: 1,
      },
      {
        id: 'employee-photo',
        type: 'image',
        x: 0.2,
        y: 0.65,
        width: 0.9,
        height: 1.35,
        source: '{{employee_photo}}',
        borderColor: '#d4af37',
        borderWidth: 3,
      },
      {
        id: 'employee-name',
        type: 'text',
        x: 1.25,
        y: 0.65,
        width: 1.9,
        height: 0.25,
        text: '{{employee_name}}',
        fontSize: 13,
        fontWeight: 'bold',
        color: '#2c2c2c',
        align: 'left',
      },
      {
        id: 'employee-id',
        type: 'text',
        x: 1.25,
        y: 0.93,
        width: 1.9,
        height: 0.15,
        text: '{{employee_id}}',
        fontSize: 10,
        fontWeight: 'bold',
        color: '#d4af37',
        align: 'left',
      },
      {
        id: 'designation',
        type: 'text',
        x: 1.25,
        y: 1.11,
        width: 1.9,
        height: 0.15,
        text: '{{designation_name}}',
        fontSize: 9,
        color: '#666666',
        align: 'left',
      },
      {
        id: 'location',
        type: 'text',
        x: 1.25,
        y: 1.29,
        width: 1.9,
        height: 0.15,
        text: '{{location_name}}',
        fontSize: 9,
        color: '#666666',
        align: 'left',
      },
      {
        id: 'bottom-accent',
        type: 'rectangle',
        x: 0,
        y: 2.01,
        width: 3.375,
        height: 0.115,
        backgroundColor: '#d4af37',
      },
      {
        id: 'qr-code',
        type: 'qrcode',
        x: 2.8,
        y: 1.55,
        width: 0.45,
        height: 0.45,
        source: '{{verification_url}}',
      },
    ],
  },

  // 9. Vertical Name Badge
  {
    id: 'template-vertical-badge',
    name: 'Vertical Badge',
    category: 'Specialized',
    description: 'Vertical orientation for lanyard wear',
    width: 2.125,
    height: 3.375,
    backgroundColor: '#ffffff',
    isActive: true,
    isDefault: false,
    elements: [
      {
        id: 'header',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 2.125,
        height: 0.5,
        backgroundColor: '#003d99',
      },
      {
        id: 'company-name',
        type: 'text',
        x: 0.1,
        y: 0.08,
        width: 1.925,
        height: 0.35,
        text: '{{company_name}}',
        fontSize: 11,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'center',
      },
      {
        id: 'employee-photo',
        type: 'image',
        x: 0.2,
        y: 0.65,
        width: 1.725,
        height: 1.5,
        source: '{{employee_photo}}',
        borderColor: '#003d99',
        borderWidth: 2,
      },
      {
        id: 'info-bg',
        type: 'rectangle',
        x: 0.1,
        y: 2.2,
        width: 1.925,
        height: 1.075,
        backgroundColor: '#f0f0f0',
      },
      {
        id: 'employee-name',
        type: 'text',
        x: 0.2,
        y: 2.3,
        width: 1.725,
        height: 0.25,
        text: '{{employee_name}}',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#000000',
        align: 'center',
      },
      {
        id: 'designation',
        type: 'text',
        x: 0.2,
        y: 2.58,
        width: 1.725,
        height: 0.2,
        text: '{{designation_name}}',
        fontSize: 9,
        color: '#333333',
        align: 'center',
      },
      {
        id: 'employee-id',
        type: 'text',
        x: 0.2,
        y: 2.81,
        width: 1.725,
        height: 0.15,
        text: 'ID: {{employee_id}}',
        fontSize: 8,
        fontWeight: 'bold',
        color: '#003d99',
        align: 'center',
      },
      {
        id: 'qr-code',
        type: 'qrcode',
        x: 0.5,
        y: 3.0,
        width: 1.125,
        height: 0.35,
        source: '{{verification_url}}',
      },
    ],
  },

  // 10. Dual Photo
  {
    id: 'template-dual-photo',
    name: 'Dual Photo',
    category: 'Specialized',
    description: 'Space for two photos - ID and candid',
    width: 3.375,
    height: 2.125,
    backgroundColor: '#ffffff',
    isActive: true,
    isDefault: false,
    elements: [
      {
        id: 'header',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 3.375,
        height: 0.4,
        backgroundColor: '#003d99',
      },
      {
        id: 'company-name',
        type: 'text',
        x: 0.15,
        y: 0.08,
        width: 3.075,
        height: 0.25,
        text: '{{company_name}}',
        fontSize: 13,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'left',
      },
      {
        id: 'photo-1-label',
        type: 'text',
        x: 0.15,
        y: 0.45,
        width: 0.5,
        height: 0.12,
        text: 'ID Photo',
        fontSize: 8,
        fontWeight: 'bold',
        color: '#666666',
        align: 'left',
      },
      {
        id: 'photo-1',
        type: 'image',
        x: 0.15,
        y: 0.6,
        width: 0.8,
        height: 1.0,
        source: '{{employee_photo}}',
        borderColor: '#003d99',
        borderWidth: 1,
      },
      {
        id: 'photo-2-label',
        type: 'text',
        x: 1.05,
        y: 0.45,
        width: 0.5,
        height: 0.12,
        text: 'Sign Photo',
        fontSize: 8,
        fontWeight: 'bold',
        color: '#666666',
        align: 'left',
      },
      {
        id: 'photo-2',
        type: 'rectangle',
        x: 1.05,
        y: 0.6,
        width: 0.8,
        height: 1.0,
        backgroundColor: '#e0e0e0',
      },
      {
        id: 'employee-name',
        type: 'text',
        x: 2.0,
        y: 0.6,
        width: 1.225,
        height: 0.2,
        text: '{{employee_name}}',
        fontSize: 11,
        fontWeight: 'bold',
        color: '#000000',
        align: 'left',
      },
      {
        id: 'employee-id',
        type: 'text',
        x: 2.0,
        y: 0.83,
        width: 1.225,
        height: 0.15,
        text: 'ID: {{employee_id}}',
        fontSize: 9,
        fontWeight: 'bold',
        color: '#003d99',
        align: 'left',
      },
      {
        id: 'designation',
        type: 'text',
        x: 2.0,
        y: 1.02,
        width: 1.225,
        height: 0.18,
        text: '{{designation_name}}',
        fontSize: 8,
        color: '#333333',
        align: 'left',
      },
      {
        id: 'department',
        type: 'text',
        x: 2.0,
        y: 1.23,
        width: 1.225,
        height: 0.15,
        text: '{{department_name}}',
        fontSize: 8,
        color: '#666666',
        align: 'left',
      },
      {
        id: 'valid-until',
        type: 'text',
        x: 2.0,
        y: 1.4,
        width: 1.225,
        height: 0.15,
        text: 'Valid: {{id_valid_until_short}}',
        fontSize: 7,
        color: '#999999',
        align: 'left',
      },
      {
        id: 'qr-code',
        type: 'qrcode',
        x: 2.15,
        y: 1.65,
        width: 0.45,
        height: 0.45,
        source: '{{verification_url}}',
      },
    ],
  },
]
